name: GolangCI-Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.13]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run GolangCI-Lint
        uses: docker://mushus/golangci-linter:v1.0.0
